# Generated by Django 3.1.7 on 2021-04-12 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cv_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='employers',
        ),
        migrations.AddField(
            model_name='cv',
            name='liked',
            field=models.ManyToManyField(through='cv_app.BookmarkCV', to=settings.AUTH_USER_MODEL, verbose_name='В избранное'),
        ),
    ]
