# Generated by Django 3.1.7 on 2021-04-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
    ]
