# Generated by Django 3.1.7 on 2021-04-09 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajax', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['title'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='bookmarkarticle',
            options={'ordering': ['user', 'obj'], 'verbose_name': 'Закладка', 'verbose_name_plural': 'Закладки'},
        ),
    ]
