# Generated by Django 3.1.7 on 2021-04-11 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Закладка',
                'verbose_name_plural': 'Закладки',
                'ordering': ['user', 'obj'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy', models.CharField(max_length=200, verbose_name='Вакансия')),
                ('employees', models.ManyToManyField(through='job_app.BookmarkJob', to=settings.AUTH_USER_MODEL, verbose_name='Соискатели')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансия',
                'ordering': ['vacancy'],
            },
        ),
        migrations.RemoveField(
            model_name='cv',
            name='employers',
        ),
        migrations.DeleteModel(
            name='BookmarkCV',
        ),
        migrations.DeleteModel(
            name='CV',
        ),
        migrations.AddField(
            model_name='bookmarkjob',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='job_app.job', verbose_name='Вакансия'),
        ),
        migrations.AddField(
            model_name='bookmarkjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Соискатель'),
        ),
    ]
