# Generated by Django 3.1.7 on 2021-04-12 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_app', '0002_auto_20210411_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='employees',
        ),
        migrations.AddField(
            model_name='job',
            name='liked',
            field=models.ManyToManyField(through='job_app.BookmarkJob', to=settings.AUTH_USER_MODEL, verbose_name='В избранное'),
        ),
    ]
